theme: jekyll-theme-slate
title: Trevor's Portfolio
description: Welcome. Here I will showcase my projects and experience with a little more detail than my resume. Please email me if you have any questions! trevordavidbrown@gmail.com



